Movimentação da estratégia inicial
analub/mini-sumo pull request #7
Opened 2023-01-18 14:48 UTC by analub

2023-01-20 22:29 UTC, analub commented
issue #7

2023-01-31 22:56 UTC, jgabriellacerda commented on src/robot.cpp
> +      delay(200);
Não é uma boa prática usar delay pq isso impede que o resto do código execute. Você deve usar a classe Move pra fazer essa movimentações e criar uma lógica para retornar true quando a movimentação acaba e se saber quando deve passar pra próxima.

2023-01-31 22:57 UTC, jgabriellacerda commented on src/strategy.cpp
> +    if(left_motor.power>0 || right_motor.power>0)
Dentro do update deve ter a lógica de quanto tempo a movimentação está sendo executada e quando ela acaba, mas sem bloquear o código com delay ou loops.

2023-02-10 19:43 UTC, jgabriellacerda requested changes

2023-02-10 22:37 UTC, jgabriellacerda approved these changes

2023-02-10 22:37 UTC, merged